version: '3'
volumes:
  app_bundle_data:
    driver: local
services:
  app:
    image: fukata/rails:ruby2.6
    command: bash -c "rm -f /app/tmp/pids/app.pid && bundle install --jobs=4 --retry=3 && bundle exec rails server -p 3000 -b 0.0.0.0 --pid /app/tmp/pids/app.pid"
    environment:
      TZ: "/usr/share/zoneinfo/Etc/UTC"
      BUNDLE_PATH: /app/vendor/bundle/
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - app_bundle_data:/app/vendor/bundle
    tty: true
    stdin_open: true
