version: '3'
volumes:
  app_bundle_data:
    driver: local
services:
  app:
    image: fukata/rails:ruby2.6-tini
    command: bash -c "rm -f /app/tmp/pids/app.pid && bundle install --jobs=4 --retry=3 && bundle exec rails server -p 3000 -b 0.0.0.0 --pid /app/tmp/pids/app.pid"
    environment:
      TZ: "/usr/share/zoneinfo/Etc/UTC"
      BUNDLE_PATH: /app/vendor/bundle/
      TEST_BROWSER: '' # browserstack, selenium-grid (default: headless_chrome)
      BROWSERSTACK_BROWSER_ID: 1 # IE11
      SELENIUM_HUB_HOST: Selenium Hubのホスト
      SELENIUM_HUB_PORT: 4444
      TEST_APP_PORT: 33333 # 下のseleium-grid用のポートと同じにする
    ports:
      - "3000:3000"
      - "33333:33333" # selenium-grid用
    volumes:
      - .:/app
      - app_bundle_data:/app/vendor/bundle
    tty: true
    stdin_open: true
